remote_theme: nxrix/theme

#baseurl: ""
#permalink: pretty
#kramdown:
#  syntax_highlighter_opts:
#    span:
#      line_numbers: false
#    block:
#      line_numbers: true
#      start_line: 1
