title: Nxrix
email: nxrixz@gmail.com
description: >
  Hello World

baseurl: ""

url: "https://nxrix.github.io/"

twitter_username: ZNxrix
github_username:  Nxrix
theme: null
permalink: pretty
collections:
  pages:
    output: true
  projects:
    output: true
  games:
    output: true
  tools:
    output: true

kramdown:
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
