title: Nxrix
email: nxrixz@gmail.com
description: >
  Hello World

baseurl: ""

url: "http://nxrix.github.io"

twitter_username: ZNxrix
github_username:  Nxrix
theme: null
permalink: pretty
collections:
  pages:
    output: true
  projects:
    output: true
  games:
    output: true
  tools:
    output: true
